openapi: 3.0.3
info:
  title: Twitter Clone API
  version: 1.0.0
  description: API REST para el clon de Twitter/X
paths:
  /api/auth/login/:
    post:
      operationId: auth_login_create
      tags:
      - auth
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/auth/logout/:
    post:
      operationId: auth_logout_create
      tags:
      - auth
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
  /api/auth/profile/{username}/:
    get:
      operationId: auth_profile_retrieve
      parameters:
      - in: path
        name: username
        schema:
          type: string
        required: true
      tags:
      - auth
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
    put:
      operationId: auth_profile_update
      parameters:
      - in: path
        name: username
        schema:
          type: string
        required: true
      tags:
      - auth
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
  /api/auth/profile/{username}/follow/:
    post:
      operationId: auth_profile_follow_create
      parameters:
      - in: path
        name: username
        schema:
          type: string
        required: true
      tags:
      - auth
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
  /api/auth/profile/{username}/followers/:
    get:
      operationId: auth_profile_followers_retrieve
      parameters:
      - in: path
        name: username
        schema:
          type: string
        required: true
      tags:
      - auth
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
  /api/auth/profile/{username}/following/:
    get:
      operationId: auth_profile_following_retrieve
      parameters:
      - in: path
        name: username
        schema:
          type: string
        required: true
      tags:
      - auth
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
  /api/auth/register/:
    post:
      operationId: auth_register_create
      tags:
      - auth
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/search/users/:
    get:
      operationId: search_users_retrieve
      tags:
      - search
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
  /api/tweets/:
    get:
      operationId: tweets_retrieve
      tags:
      - tweets
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
    post:
      operationId: tweets_create
      tags:
      - tweets
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
  /api/tweets/{id}/:
    get:
      operationId: tweets_retrieve_2
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - tweets
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
    delete:
      operationId: tweets_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - tweets
      security:
      - jwtAuth: []
      responses:
        '204':
          description: No response body
  /api/tweets/{id}/like/:
    post:
      operationId: tweets_like_create
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - tweets
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
  /api/tweets/timeline/:
    get:
      operationId: tweets_timeline_retrieve
      tags:
      - tweets
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
components:
  securitySchemes:
    jwtAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
